//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MathGrammar.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

namespace CustomerOnboarding.BusinessLibrary.Parsing.MathGrammar
{

    [System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
    [System.CLSCompliant(false)]
    public partial class MathGrammarParser : Parser
    {
        protected static DFA[] decisionToDFA;
        protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
        public const int
            T__0 = 1, T__1 = 2, T__2 = 3, T__3 = 4, T__4 = 5, T__5 = 6, T__6 = 7, T__7 = 8, T__8 = 9,
            T__9 = 10, T__10 = 11, T__11 = 12, T__12 = 13, T__13 = 14, T__14 = 15, T__15 = 16, T__16 = 17,
            T__17 = 18, T__18 = 19, T__19 = 20, T__20 = 21, T__21 = 22, T__22 = 23, T__23 = 24,
            T__24 = 25, T__25 = 26, T__26 = 27, NUMBER = 28, WS = 29;
        public const int
            RULE_start = 0, RULE_expression = 1, RULE_variable = 2;
        public static readonly string[] ruleNames = {
        "start", "expression", "variable"
    };

        private static readonly string[] _LiteralNames = {
        null, "'*'", "'/'", "'+'", "'-'", "'('", "')'", "'of'", "'Basic Salary'",
        "'Base Hourly Rate'", "'Number Of Days Per Month'", "'Number Of Hours Per Day'",
        "'Percentage'", "'Percent'", "'Fixed Amount'", "'Fixed Rate'", "'Rate Per Kilometer'",
        "'Rate Per Litre'", "'Number Of Kilometers'", "'Number Of Litres'", "'Number Of Months Served'",
        "'Number Of Years Served'", "'Number Of Leave Days Accrued'", "'Number Of Leave Days Commuted'",
        "'Gross Pay'", "'Total Hours Worked'", "'Total Sales'", "'Multiplier'"
    };
        private static readonly string[] _SymbolicNames = {
        null, null, null, null, null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null, null, null, null, null,
        null, null, null, null, "NUMBER", "WS"
    };
        public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

        [NotNull]
        public override IVocabulary Vocabulary
        {
            get
            {
                return DefaultVocabulary;
            }
        }

        public override string GrammarFileName { get { return "MathGrammar.g4"; } }

        public override string[] RuleNames { get { return ruleNames; } }

        public override int[] SerializedAtn { get { return _serializedATN; } }

        static MathGrammarParser()
        {
            decisionToDFA = new DFA[_ATN.NumberOfDecisions];
            for (int i = 0; i < _ATN.NumberOfDecisions; i++)
            {
                decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
            }
        }

        public MathGrammarParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

        public MathGrammarParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
        : base(input, output, errorOutput)
        {
            Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
        }

        public partial class StartContext : ParserRuleContext
        {
            [System.Diagnostics.DebuggerNonUserCode]
            public ExpressionContext expression()
            {
                return GetRuleContext<ExpressionContext>(0);
            }
            [System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(MathGrammarParser.Eof, 0); }
            public StartContext(ParserRuleContext parent, int invokingState)
                : base(parent, invokingState)
            {
            }
            public override int RuleIndex { get { return RULE_start; } }
            [System.Diagnostics.DebuggerNonUserCode]
            public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor)
            {
                IMathGrammarVisitor<TResult> typedVisitor = visitor as IMathGrammarVisitor<TResult>;
                if (typedVisitor != null) return typedVisitor.VisitStart(this);
                else return visitor.VisitChildren(this);
            }
        }

        [RuleVersion(0)]
        public StartContext start()
        {
            StartContext _localctx = new StartContext(Context, State);
            EnterRule(_localctx, 0, RULE_start);
            try
            {
                EnterOuterAlt(_localctx, 1);
                {
                    State = 6;
                    expression(0);
                    State = 7;
                    Match(Eof);
                }
            }
            catch (RecognitionException re)
            {
                _localctx.exception = re;
                ErrorHandler.ReportError(this, re);
                ErrorHandler.Recover(this, re);
            }
            finally
            {
                ExitRule();
            }
            return _localctx;
        }

        public partial class ExpressionContext : ParserRuleContext
        {
            [System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(MathGrammarParser.NUMBER, 0); }
            [System.Diagnostics.DebuggerNonUserCode]
            public VariableContext variable()
            {
                return GetRuleContext<VariableContext>(0);
            }
            [System.Diagnostics.DebuggerNonUserCode]
            public ExpressionContext[] expression()
            {
                return GetRuleContexts<ExpressionContext>();
            }
            [System.Diagnostics.DebuggerNonUserCode]
            public ExpressionContext expression(int i)
            {
                return GetRuleContext<ExpressionContext>(i);
            }
            public ExpressionContext(ParserRuleContext parent, int invokingState)
                : base(parent, invokingState)
            {
            }
            public override int RuleIndex { get { return RULE_expression; } }
            [System.Diagnostics.DebuggerNonUserCode]
            public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor)
            {
                IMathGrammarVisitor<TResult> typedVisitor = visitor as IMathGrammarVisitor<TResult>;
                if (typedVisitor != null) return typedVisitor.VisitExpression(this);
                else return visitor.VisitChildren(this);
            }
        }

        [RuleVersion(0)]
        public ExpressionContext expression()
        {
            return expression(0);
        }

        private ExpressionContext expression(int _p)
        {
            ParserRuleContext _parentctx = Context;
            int _parentState = State;
            ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
            ExpressionContext _prevctx = _localctx;
            int _startState = 2;
            EnterRecursionRule(_localctx, 2, RULE_expression, _p);
            try
            {
                int _alt;
                EnterOuterAlt(_localctx, 1);
                {
                    State = 16;
                    ErrorHandler.Sync(this);
                    switch (Interpreter.AdaptivePredict(TokenStream, 0, Context))
                    {
                        case 1:
                            {
                            }
                            break;
                        case 2:
                            {
                                State = 10;
                                Match(NUMBER);
                            }
                            break;
                        case 3:
                            {
                                State = 11;
                                variable();
                            }
                            break;
                        case 4:
                            {
                                State = 12;
                                Match(T__4);
                                State = 13;
                                expression(0);
                                State = 14;
                                Match(T__5);
                            }
                            break;
                    }
                    Context.Stop = TokenStream.LT(-1);
                    State = 35;
                    ErrorHandler.Sync(this);
                    _alt = Interpreter.AdaptivePredict(TokenStream, 2, Context);
                    while (_alt != 2 && _alt != global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER)
                    {
                        if (_alt == 1)
                        {
                            if (ParseListeners != null)
                                TriggerExitRuleEvent();
                            _prevctx = _localctx;
                            {
                                State = 33;
                                ErrorHandler.Sync(this);
                                switch (Interpreter.AdaptivePredict(TokenStream, 1, Context))
                                {
                                    case 1:
                                        {
                                            _localctx = new ExpressionContext(_parentctx, _parentState);
                                            PushNewRecursionContext(_localctx, _startState, RULE_expression);
                                            State = 18;
                                            if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
                                            State = 19;
                                            Match(T__0);
                                            State = 20;
                                            expression(7);
                                        }
                                        break;
                                    case 2:
                                        {
                                            _localctx = new ExpressionContext(_parentctx, _parentState);
                                            PushNewRecursionContext(_localctx, _startState, RULE_expression);
                                            State = 21;
                                            if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
                                            State = 22;
                                            Match(T__1);
                                            State = 23;
                                            expression(6);
                                        }
                                        break;
                                    case 3:
                                        {
                                            _localctx = new ExpressionContext(_parentctx, _parentState);
                                            PushNewRecursionContext(_localctx, _startState, RULE_expression);
                                            State = 24;
                                            if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
                                            State = 25;
                                            Match(T__2);
                                            State = 26;
                                            expression(5);
                                        }
                                        break;
                                    case 4:
                                        {
                                            _localctx = new ExpressionContext(_parentctx, _parentState);
                                            PushNewRecursionContext(_localctx, _startState, RULE_expression);
                                            State = 27;
                                            if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
                                            State = 28;
                                            Match(T__3);
                                            State = 29;
                                            expression(4);
                                        }
                                        break;
                                    case 5:
                                        {
                                            _localctx = new ExpressionContext(_parentctx, _parentState);
                                            PushNewRecursionContext(_localctx, _startState, RULE_expression);
                                            State = 30;
                                            if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
                                            State = 31;
                                            Match(T__6);
                                            State = 32;
                                            expression(2);
                                        }
                                        break;
                                }
                            }
                        }
                        State = 37;
                        ErrorHandler.Sync(this);
                        _alt = Interpreter.AdaptivePredict(TokenStream, 2, Context);
                    }
                }
            }
            catch (RecognitionException re)
            {
                _localctx.exception = re;
                ErrorHandler.ReportError(this, re);
                ErrorHandler.Recover(this, re);
            }
            finally
            {
                UnrollRecursionContexts(_parentctx);
            }
            return _localctx;
        }

        public partial class VariableContext : ParserRuleContext
        {
            public VariableContext(ParserRuleContext parent, int invokingState)
                : base(parent, invokingState)
            {
            }
            public override int RuleIndex { get { return RULE_variable; } }
            [System.Diagnostics.DebuggerNonUserCode]
            public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor)
            {
                IMathGrammarVisitor<TResult> typedVisitor = visitor as IMathGrammarVisitor<TResult>;
                if (typedVisitor != null) return typedVisitor.VisitVariable(this);
                else return visitor.VisitChildren(this);
            }
        }

        [RuleVersion(0)]
        public VariableContext variable()
        {
            VariableContext _localctx = new VariableContext(Context, State);
            EnterRule(_localctx, 4, RULE_variable);
            try
            {
                State = 59;
                ErrorHandler.Sync(this);
                switch (Interpreter.AdaptivePredict(TokenStream, 3, Context))
                {
                    case 1:
                        EnterOuterAlt(_localctx, 1);
                        {
                        }
                        break;
                    case 2:
                        EnterOuterAlt(_localctx, 2);
                        {
                            State = 39;
                            Match(T__7);
                        }
                        break;
                    case 3:
                        EnterOuterAlt(_localctx, 3);
                        {
                            State = 40;
                            Match(T__8);
                        }
                        break;
                    case 4:
                        EnterOuterAlt(_localctx, 4);
                        {
                            State = 41;
                            Match(T__9);
                        }
                        break;
                    case 5:
                        EnterOuterAlt(_localctx, 5);
                        {
                            State = 42;
                            Match(T__10);
                        }
                        break;
                    case 6:
                        EnterOuterAlt(_localctx, 6);
                        {
                            State = 43;
                            Match(T__11);
                        }
                        break;
                    case 7:
                        EnterOuterAlt(_localctx, 7);
                        {
                            State = 44;
                            Match(T__12);
                        }
                        break;
                    case 8:
                        EnterOuterAlt(_localctx, 8);
                        {
                            State = 45;
                            Match(T__13);
                        }
                        break;
                    case 9:
                        EnterOuterAlt(_localctx, 9);
                        {
                            State = 46;
                            Match(T__14);
                        }
                        break;
                    case 10:
                        EnterOuterAlt(_localctx, 10);
                        {
                            State = 47;
                            Match(T__15);
                        }
                        break;
                    case 11:
                        EnterOuterAlt(_localctx, 11);
                        {
                            State = 48;
                            Match(T__16);
                        }
                        break;
                    case 12:
                        EnterOuterAlt(_localctx, 12);
                        {
                            State = 49;
                            Match(T__17);
                        }
                        break;
                    case 13:
                        EnterOuterAlt(_localctx, 13);
                        {
                            State = 50;
                            Match(T__18);
                        }
                        break;
                    case 14:
                        EnterOuterAlt(_localctx, 14);
                        {
                            State = 51;
                            Match(T__19);
                        }
                        break;
                    case 15:
                        EnterOuterAlt(_localctx, 15);
                        {
                            State = 52;
                            Match(T__20);
                        }
                        break;
                    case 16:
                        EnterOuterAlt(_localctx, 16);
                        {
                            State = 53;
                            Match(T__21);
                        }
                        break;
                    case 17:
                        EnterOuterAlt(_localctx, 17);
                        {
                            State = 54;
                            Match(T__22);
                        }
                        break;
                    case 18:
                        EnterOuterAlt(_localctx, 18);
                        {
                            State = 55;
                            Match(T__23);
                        }
                        break;
                    case 19:
                        EnterOuterAlt(_localctx, 19);
                        {
                            State = 56;
                            Match(T__24);
                        }
                        break;
                    case 20:
                        EnterOuterAlt(_localctx, 20);
                        {
                            State = 57;
                            Match(T__25);
                        }
                        break;
                    case 21:
                        EnterOuterAlt(_localctx, 21);
                        {
                            State = 58;
                            Match(T__26);
                        }
                        break;
                }
            }
            catch (RecognitionException re)
            {
                _localctx.exception = re;
                ErrorHandler.ReportError(this, re);
                ErrorHandler.Recover(this, re);
            }
            finally
            {
                ExitRule();
            }
            return _localctx;
        }

        public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex)
        {
            switch (ruleIndex)
            {
                case 1: return expression_sempred((ExpressionContext)_localctx, predIndex);
            }
            return true;
        }
        private bool expression_sempred(ExpressionContext _localctx, int predIndex)
        {
            switch (predIndex)
            {
                case 0: return Precpred(Context, 6);
                case 1: return Precpred(Context, 5);
                case 2: return Precpred(Context, 4);
                case 3: return Precpred(Context, 3);
                case 4: return Precpred(Context, 1);
            }
            return true;
        }

        private static int[] _serializedATN = {
        4,1,29,62,2,0,7,0,2,1,7,1,2,2,7,2,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,
        1,1,3,1,17,8,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
        1,1,5,1,34,8,1,10,1,12,1,37,9,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,
        2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,60,8,2,1,2,0,1,2,3,0,
        2,4,0,0,86,0,6,1,0,0,0,2,16,1,0,0,0,4,59,1,0,0,0,6,7,3,2,1,0,7,8,5,0,0,
        1,8,1,1,0,0,0,9,17,6,1,-1,0,10,17,5,28,0,0,11,17,3,4,2,0,12,13,5,5,0,0,
        13,14,3,2,1,0,14,15,5,6,0,0,15,17,1,0,0,0,16,9,1,0,0,0,16,10,1,0,0,0,16,
        11,1,0,0,0,16,12,1,0,0,0,17,35,1,0,0,0,18,19,10,6,0,0,19,20,5,1,0,0,20,
        34,3,2,1,7,21,22,10,5,0,0,22,23,5,2,0,0,23,34,3,2,1,6,24,25,10,4,0,0,25,
        26,5,3,0,0,26,34,3,2,1,5,27,28,10,3,0,0,28,29,5,4,0,0,29,34,3,2,1,4,30,
        31,10,1,0,0,31,32,5,7,0,0,32,34,3,2,1,2,33,18,1,0,0,0,33,21,1,0,0,0,33,
        24,1,0,0,0,33,27,1,0,0,0,33,30,1,0,0,0,34,37,1,0,0,0,35,33,1,0,0,0,35,
        36,1,0,0,0,36,3,1,0,0,0,37,35,1,0,0,0,38,60,1,0,0,0,39,60,5,8,0,0,40,60,
        5,9,0,0,41,60,5,10,0,0,42,60,5,11,0,0,43,60,5,12,0,0,44,60,5,13,0,0,45,
        60,5,14,0,0,46,60,5,15,0,0,47,60,5,16,0,0,48,60,5,17,0,0,49,60,5,18,0,
        0,50,60,5,19,0,0,51,60,5,20,0,0,52,60,5,21,0,0,53,60,5,22,0,0,54,60,5,
        23,0,0,55,60,5,24,0,0,56,60,5,25,0,0,57,60,5,26,0,0,58,60,5,27,0,0,59,
        38,1,0,0,0,59,39,1,0,0,0,59,40,1,0,0,0,59,41,1,0,0,0,59,42,1,0,0,0,59,
        43,1,0,0,0,59,44,1,0,0,0,59,45,1,0,0,0,59,46,1,0,0,0,59,47,1,0,0,0,59,
        48,1,0,0,0,59,49,1,0,0,0,59,50,1,0,0,0,59,51,1,0,0,0,59,52,1,0,0,0,59,
        53,1,0,0,0,59,54,1,0,0,0,59,55,1,0,0,0,59,56,1,0,0,0,59,57,1,0,0,0,59,
        58,1,0,0,0,60,5,1,0,0,0,4,16,33,35,59
    };

        public static readonly ATN _ATN =
            new ATNDeserializer().Deserialize(_serializedATN);


    }

}
